python data.py --gram SL --k 2 --n 1k
python data.py --gram SL --k 2 --n 10k
python data.py --gram SL --k 2 --n 100k
python data.py --gram SL --k 4 --n 100k
python data.py --gram SL --k 4 --n 10k
python data.py --gram SL --k 4 --n 1k
python data.py --gram SL --k 8 --n 1k
python data.py --gram SL --k 8 --n 10k
python data.py --gram SL --k 8 --n 100k
python data.py --gram SP --k 8 --n 100k
python data.py --gram SP --k 8 --n 10k
python data.py --gram SP --k 8 --n 1k
python data.py --gram SP --k 2 --n 1k
python data.py --gram SP --k 2 --n 10k
python data.py --gram SP --k 2 --n 100k
python data.py --gram SP --k 4 --n 100k
python data.py --gram SP --k 4 --n 10k
python data.py --gram SP --k 4 --n 1k